### ISSUE TITLE
fix(trusted-sync): Follow tip with head updates

### ISSUE THREAD

**Issue by clabby** [anton-rs/kona#315]
## Overview

Currently the `trusted-sync` binary follows tip by continuously attempting to advance the cursor, fetching the next block. If the cursor is at tip, this will just cause the loop to spam logs. Instead, the binary should subscribe to head updates to avoid busy waiting, and advance the cursor on head update. This will allow the service to run persistently and expressively in our infrastructure.

We can do this most ergonomically by splitting the trusted sync control flow in two stages. The first stage is when the starting l2 block number origin to sync from is before tip. When this is the case, we perform the iterative looping over pipeline attributes creation and origin advancing. Once L1 tip is reached, trusted-sync advances to the next stage where it subscribes to new head updates and only drives the pipeline on head advancement.

**Comment by refcell** [comment]
Moving to nice to have since this is not critical - trusted-sync follows tip well, despite a bit more verbose logging.

**Comment by refcell** [comment]
`trusted-sync` is dead, long live `trusted-sync` https://github.com/anton-rs/kona/pull/621
