### ISSUE TITLE
Fix: Resolving compile error of derive crate with 'online' feature

### ISSUE THREAD

**Issue by raindust** [anton-rs/kona#480]
In a dependent Cargo crate, using the following dependency specification:
```
kona-derive = { git = "https://github.com/anton-rs/kona.git", branch = "main", features = ["online"] }
```

This results in the following compile error:
```
error[E0432]: unresolved import `revm::primitives::kzg`
  --> ... crates/primitives/src/sidecar.rs:14:23
   |
14 | use revm::primitives::kzg::EnvKzgSettings;
   |                       ^^^ could not find `kzg` in `primitives`
   |
```

The root cause of this error is that the derive crate doesn't enable the "c-kzg" feature, which is required for the code to compile correctly. I plan to submit a pull request (PR) to fix this issue.

**Comment by refcell** [comment]
This is fixed by https://github.com/anton-rs/kona/pull/482
