### ISSUE TITLE
[HOLOCENE] `L1BlockInfoTx::Holocene` derivation

### ISSUE THREAD

**Issue by clabby** [anton-rs/kona#594]
## Overview

> [!NOTE]
> Depends on #595 

As a part of holocene, the `L1BlockInfoTx` has a new variant. `L2ChainProvider::system_config_by_number` relies on `OpBlock::to_system_config` to fill out the `SystemConfig`, and we will need to add the new variant into the `match` [here](https://github.com/anton-rs/kona/blob/9e9c002dd18f1215a8ee16808a7787c71eb7d8f8/crates/derive/src/block.rs#L138-L155).

**Comment by refcell** [comment]
Pending: https://github.com/ethereum-optimism/specs/pull/404

**Comment by clabby** [comment]
cancelled
