### ISSUE TITLE
[HOLOCENE] Upgrade transactions

### ISSUE THREAD

**Issue by clabby** [anton-rs/kona#598]
## Overview

Holocene adds several new upgrade transactions to the derivation pipeline's attributes builder. These are mentioned in the [derivation spec](https://specs.optimism.io/protocol/holocene/derivation.html#network-upgrade-automation-transactions), but are not yet defined. Once they are, this issue will be updated with a link to them.

**Comment by refcell** [comment]
Cancelled https://github.com/ethereum-optimism/specs/pull/409
