### ISSUE TITLE
chore(executor): Test Output Root Computation

### ISSUE THREAD

**Issue by refcell** [anton-rs/kona#679]
### Description

Add a test to the `kona-executor` lib that uses a block where the output root was confirmed onchain to test the `compute_output_root`.

Example (verify at index 8833 on `0xdfe97868233d1aa22e815a266982f2cf17685a27`):
- Block: `121184863`
- Output Root: `0x3ea8b0e09b39e9daa1b1520fe59faef02de3656d230d876544952cbc44d6d71f`

This should be placed at the bottom of [`lib.rs`](https://github.com/anton-rs/kona/blob/main/crates/executor/src/lib.rs#L1198C1-L1200C89).

**Comment by piotr-roslaniec** [comment]
Hi @refcell,

I'd like to contribute to [this issue](https://github.com/anton-rs/kona/compare/main...piotr-roslaniec:kona:test-root-compute?expand=1). I have a follow-up question regarding the `executor/testdata` directory - are there any utilities or instructions available for generating these test inputs?

Thanks!

**Comment by clabby** [comment]
> Hi [@refcell](https://github.com/refcell),
> 
> I'd like to [contribute](https://github.com/anton-rs/kona/compare/main...piotr-roslaniec:kona:test-root-compute?expand=1) to this issue. I have a follow-up question regarding the `executor/testdata` directory - are there any utilities or instructions available for generating these test inputs? Edit: I see someone asked about that previously here: [#607](https://github.com/anton-rs/kona/issues/607)
> 
> Thanks!

The way I did this in the past was to create an online version of the `TrieProvider` interfaces, using geth's `debug_dbGet` to back the trie-node-by-hash endpoint. This would also be a really nice test utility to have, but I've unfortunately lost the code there.

Once you have that, you can capture each trie node / bytecode preimage that is requested it and commit it to disk.

**Comment by clabby** [comment]
Going to go ahead and close this. This codepath is now covered by the action tests.
