### ISSUE TITLE
chore(derive): Move `Batch`, `SingleBatch`, and `SpanBatch` to `op-alloy-protocol`

### ISSUE THREAD

**Issue by clabby** [anton-rs/kona#695]
## Overview

Right now, `Frame` + `Channel` live in `op-alloy-protocol`, but the batch types still live in `kona-derive`. We should move the following types and associated helpers into `op-alloy-protocol`:
1. `Batch`
2. `SingleBatch`
3. `SpanBatch` + sub-types.

**Comment by mahmudsudo** [comment]
can i take on this ?

**Comment by refcell** [comment]
Completed by https://github.com/anton-rs/kona/pull/746
